/* ==========================================================================
   INTERFACE STRINGS

   Every word that appears on screen but is not prose in an MDX file lives
   here. Button labels, link text, empty states, form errors, screen reader
   text, all of it. No user-facing string is written into a .astro or .tsx
   file anywhere in this project.

   To change any word on the site, it is either in an MDX file under
   src/content/, or it is here. There is no third place to look.

   House style, applied throughout:
   - American English, US date formats.
   - No em dashes.
   - No exclamation marks. No rhetorical questions as headings.
   - Errors say what to do next. They do not apologize and are never vague.
   ========================================================================== */

export const ui = {
  /* --- Global chrome ---------------------------------------------------- */
  skipToContent: "Skip to content",
  siteNavLabel: "Primary",
  footerNavLabel: "Footer",

  header: {
    /** Screen reader name for the logotype link. */
    homeLinkLabel: "Home",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    menuLabel: "Site menu",
  },

  theme: {
    /** The toggle is a single unit volume, lit or unlit, matching the stack. */
    label: "Theme",
    toLight: "Switch to light theme",
    toDark: "Switch to dark theme",
    lightName: "Light",
    darkName: "Dark",
  },

  footer: {
    emailLabel: "Email",
    linkedinLabel: "LinkedIn",
    /** %YEAR% is replaced at build time. */
    copyright: "© %YEAR% %NAME%",
    builtNote: "Set in Fraunces and Instrument Sans.",
  },

  /* --- Calls to action --------------------------------------------------- */
  cta: {
    email: "Email %NAME%",
    downloadCv: "Download CV, PDF",
    downloadCvPending: "CV coming soon",
    fullCv: "Full CV",
    readCaseStudy: "Read the case study",
    allCaseStudies: "All case studies",
    moreAbout: "More about how I work",
    backToJournal: "Journal",
    backToWork: "Case studies",
    /* The arrows are part of the label rather than typed into the component,
       so these read exactly as written here. Decorative arrows that are
       generated by CSS (the "read more" links) are presentational and are not
       duplicated here: a screen reader never announces those. */
    previous: "← Previous",
    next: "Next →",
    home: "Back to home",
  },

  /* --- The 3D building ---------------------------------------------------
     The canvas is hidden from assistive technology. This is the text a
     screen reader gets instead, so the image is never just a blank. */
  scene: {
    description:
      "A cutaway illustration of an apartment building, with its front wall removed to show the floors and the individual units inside. Each unit carries its door number, and the occupied ones are lit from within. It turns slowly as the page scrolls.",
  },

  /* --- Lease-up figures, on the Experience page --------------------------- */
  stack: {
    regionLabel: "Lease-up occupancy",
    caption: "Units leased against total, by floor.",
  },

  /* --- Rent roll strip ---------------------------------------------------
     Column labels for the figures on home. The figures themselves come from
     src/content/home/rent-roll.mdx. */
  rentRoll: {
    regionLabel: "Lease-up summary",
  },

  /* --- Career spine ------------------------------------------------------
     Set as a rent roll: dated rows with typed columns, not a dotted line. */
  career: {
    colPeriod: "Period",
    colRole: "Role",
    colUnits: "Units",
    colProgram: "Program",
    empty:
      "No roles yet. Add one by copying a file in src/content/experience/ and editing the frontmatter.",
  },

  /* --- Case studies ------------------------------------------------------ */
  work: {
    situation: "On arrival",
    action: "What I changed",
    outcome: "Result",
    metrics: "Summary",
    empty:
      "No case studies yet. Add one by copying src/content/work/_template.mdx and editing the frontmatter.",
  },

  /* --- Credentials -------------------------------------------------------- */
  credentials: {
    issuedBy: "Issued by",
    systemsHeading: "Systems",
    empty:
      "No credentials yet. Add one by copying a file in src/content/credentials/ and editing the frontmatter.",
  },

  /* --- Journal ------------------------------------------------------------ */
  journal: {
    allTags: "All",
    filterLabel: "Filter by topic",
    empty: "No posts yet.",
    emptyFiltered: "No posts with that tag. Choose All to see everything.",
    rssLabel: "RSS feed",
    postedOn: "Posted",
    /** Separator between date and topic in the post header. */
    metaSeparator: " · ",
  },

  /* --- Contact form -------------------------------------------------------
     Every field has a persistent visible label. Placeholder-only labeling
     is a failure, so no field here relies on one. */
  contact: {
    nameLabel: "Your name",
    emailLabel: "Your email",
    orgLabel: "Company",
    orgOptional: "Optional",
    messageLabel: "Message",
    submit: "Send message",
    submitting: "Sending",
    directHeading: "Or reach me directly",
    /** Honeypot. Hidden from sight and from screen readers. */
    honeypotLabel: "Leave this field empty",

    success: {
      heading: "Message sent",
      body: "I read everything that comes through here and will reply within two business days.",
    },

    errors: {
      nameRequired: "Enter your name.",
      emailRequired: "Enter your email address.",
      emailInvalid: "Enter an email address in the form name@company.com.",
      messageRequired: "Enter a message.",
      messageTooShort: "Add a little more detail, at least 20 characters.",
      messageTooLong: "Shorten this to 4000 characters or fewer.",
      turnstileRequired: "Complete the verification check below the message field.",
      turnstileFailed: "The verification check did not pass. Reload the page and try again.",
      rateLimited: "Too many messages sent from this connection. Try again in an hour.",
      server: "The message did not send. Email me directly at the address below.",
      network: "No connection. Check your network and send again.",
    },

    /** Announced to screen readers when errors appear. */
    errorSummaryHeading: "Fix these before sending",
  },

  /* --- 404 ---------------------------------------------------------------- */
  notFound: {
    code: "404",
    heading: "That page is not here",
    body: "The link may be out of date, or the address may have a typo in it.",
  },

  /* --- Placeholder notices -------------------------------------------------
     Shown only in development, never in a production build. They exist so an
     unfilled value is impossible to miss while editing. */
  placeholder: {
    badge: "Not filled in yet",
    hint: "Edit src/content/site.ts",
  },
} as const;

/** Substitutes %TOKEN% placeholders in a UI string. */
export function fill(
  template: string,
  values: Record<string, string | number>,
): string {
  return Object.entries(values).reduce(
    (out, [key, value]) => out.split(`%${key}%`).join(String(value)),
    template,
  );
}
